FROM node:18-slim

# Install dependencies
RUN apt-get update && apt-get install -y \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxi6 \
    libxtst6 \
    libnss3 \
    libxrandr2 \
    libasound2 \
    libpangocairo-1.0-0 \
    libatk1.0-0 \
    libcups2 \
    libxss1 \
    libgtk-3-0 \
    libgbm1 \
    libpangoft2-1.0-0 \
    libgtk-3-dev \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Install Puppeteer
RUN npm install puppeteer

# Set working directory
WORKDIR /app

# Copy your project files
COPY . .

# Start the app
CMD ["node", "server.js"]
